-- Migration: Import Wallet by Keypair
-- Date: 2026-06-01
-- Status: CODE + DOCUMENTATION (no destructive schema changes)

-- Purpose:
--   Allow users to import an existing Solana wallet by supplying its secret key.
--   The secret key is encrypted with AES-256-GCM (lib/wallet/encryption.ts) and
--   stored in public.user_wallets exactly like a minted custodial wallet, so the
--   platform can sign transactions server-side on the user's behalf.

-- Existing table structure (verified before writing — no DDL required):
--   public.user_wallets
--     user_id              uuid  PRIMARY KEY  -> exactly one wallet row per user
--     public_key           text  UNIQUE       -> a public key can belong to only one user
--     encrypted_secret_key text
--     iv                   text
--     auth_tag             text
--     origin               text  ('minted' | 'external' | 'imported')
--     exported_at          timestamptz
--     created_at           timestamptz
--     updated_at           timestamptz

-- Data operation performed by app/api/wallet/import/route.ts -> importWallet():
--   1. Validate the supplied secret key (base58 string OR JSON byte array).
--   2. Derive the Keypair and its public key.
--   3. Encrypt the base58 secret key.
--   4. UPSERT into user_wallets ON CONFLICT (user_id):
--        INSERT (user_id, public_key, encrypted_secret_key, iv, auth_tag, origin='imported')
--        ON CONFLICT (user_id) DO UPDATE SET the above + updated_at = now()
--      Because user_id is the PRIMARY KEY, importing REPLACES the user's active
--      custodial wallet. The public_key UNIQUE constraint prevents importing a key
--      that already belongs to another account (handled gracefully in code).
--   5. UPDATE profiles.wallet_address to the imported public key.

-- Document the supported origin values on the column for future maintainers.
COMMENT ON COLUMN public.user_wallets.origin IS
  'How the wallet was provisioned: minted (generated by platform), external (wallet-adapter connect), imported (user supplied secret key, encrypted at rest).';
